all: human derp luke nth predict

human: ju_human.cpp ju_library.cpp ju.h
	g++ -o human ju_human.cpp ju_library.cpp

derp: ju_example.cpp ju_library.cpp ju.h
	g++ -o derp ju_example.cpp ju_library.cpp

luke: ju_luke.cpp ju_library.cpp ju.h
	g++ -o ju_luke ju_luke.cpp ju_library.cpp

nth: ju_nth.cpp ju_library.cpp ju.h
	g++ -o ju_nth ju_nth.cpp ju_library.cpp

predict: ju_predict.cpp ju_library.cpp ju.h
	g++ -o ju_predict ju_predict.cpp ju_library.cpp
